##
## EPITECH PROJECT, 2018
## Aracde
## File description:
## Epitech project
##

all: $(OBJ)
	make -C ./src/Snake

clean:
	make clean -C ./src/Snake

fclean: clean
	make fclean -C ./src/Snake

re: fclean all

.PHONY: all clean fclean re
