##
## EPITECH PROJECT, 2018
## Aracde
## File description:
## Epitech project
##

all: $(OBJ)
	make -sC ./src/ncurses

clean:
	make clean -sC ./src/ncurses

fclean: clean
	make fclean -sC ./src/ncurses

re: fclean all

.PHONY: all clean fclean re
