##
## EPITECH PROJECT, 2018
## Aracde
## File description:
## Epitech project
##

all: $(OBJ)
	make -sC ./src/test

clean:
	make clean -sC ./src/test

fclean: clean
	make fclean -sC ./src/test

re: fclean all

.PHONY: all clean fclean re
